### ISSUE TITLE
How to validate if the correct packages have been installed?

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/packse#157]
I have a basic test framework working for pip, and I am now debugging the results.

One thing I am immediately confused on, is I expected that "expected" would give the success conditions for each scenario. But looking at example.json: https://github.com/astral-sh/packse/blob/main/scenarios/example.json this is not the case. Expected includes "b": "3.0.0", but the success criteria would be "b" equal to "2.0.0".

Is this just a bug in this example or am I misreading the scenarios?

**Comment by zanieb** [comment]
All the scenarios have their version encoded in `<module>.__version__` or you can use importlib metadata to retrieve it.

The `example` is indeed incorrect, I can fix that. We do not use that example in any of our tests. All the other scenarios should be correct.

**Comment by notatallshaw** [comment]
Ah, I started with example because it was the simplest and assumed it would be a correct example! Feel free to close this issue.

I am now going through the whole test suite and filing other issues as I find them. Hope that is appreciated.

**Comment by zanieb** [comment]
It's definitely appreciated! I'll respond as I can, although I may not get to them all until Monday.

**Comment by notatallshaw** [comment]
> It's definitely appreciated! I'll respond as I can, although I may not get to them all until Monday.

No worries, I work on OSS in my free time not during my work hours! I don't expect quick turn arounds, most OSS projects might take days or weeks to respond...
