### ISSUE TITLE
Trying to understand "local-transitive-confounding" scenario

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/packse#159]
In the scenario "local-transitive-confounding": https://github.com/astral-sh/packse/blob/0.3.12/scenarios/local.json#L280

Has expected:

```json
"expected": {
    "satisfiable": true,
    "packages": {
        "a": "2.0.0+foo"
    },
```

But there is no package a==2.0.0+foo:

```json
"packages": {
    "a": {
        "versions": {
            "1.0.0": {
                "requires": [
                    "b==2.0.0"
                ]
            }
        }
    },
```

**Comment by zanieb** [comment]
Yes this looks incorrect, thanks for flagging! cc @BurntSushi / @charliermarsh

**Comment by charliermarsh** [comment]
For once it’s not my fault 😂

**Comment by charliermarsh** [comment]
Can fix on Monday.
